# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
PYTHON_COMPAT=(python{2_6,2_7,3_3,3_4,3_5})

inherit distutils-r1


DESCRIPTION="This is a python class to use nmap and access scan results from python3"
HOMEPAGE="https://pypi.python.org/pypi/python-nmap"
SRC_URI="https://pypi.python.org/packages/dc/f2/9e1a2953d4d824e183ac033e3d223055e40e695fa6db2cb3e94a864eaa84/${P}.tar.gz"

LICENSE="GPL-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""



