# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
PYTHON_COMPAT=(python{2_6,2_7,3_3,3_4})

inherit distutils-r1


DESCRIPTION="This is a python class to use nmap and access scan results from python3"
HOMEPAGE="http://xael.org/norman/python/python-nmap/"
SRC_URI="https://pypi.python.org/packages/source/p/python-nmap/${P}.tar.gz"

LICENSE="GPL-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""



