# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Comprehensive bindings and command line utility for the Pushover notification service"
HOMEPAGE="https://github.com/Thibauth/python-pushover"
SRC_URI="https://pypi.python.org/packages/source/p/python-pushover/${P}.tar.gz"

LICENSE="GPL-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/requests-1.0
	dev-python/setuptools"

PYTHON_MODNAME="pushover"

