# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="5"
PYTHON_COMPAT=(python{2_6,2_7,3_3,3_4,3_5})

inherit distutils-r1


DESCRIPTION="Comprehensive bindings and command line utility for the Pushover notification service"
HOMEPAGE="https://github.com/Thibauth/python-pushover"
SRC_URI="https://github.com/Thibauth/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="GPL-2"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND=">=dev-python/requests-1.0
	dev-python/setuptools"


