#!/usr/bin/env python2
from pybitcoin import address_to_new_cryptocurrency
import sys

try:
    if (sys.argv[1][0]=="M"):
        print(address_to_new_cryptocurrency(sys.argv[1], 5))
    elif (sys.argv[1][0]=="3"):
        print(address_to_new_cryptocurrency(sys.argv[1], 50))
    else:
        raise ValueError("invalid address")
except:
    raise ValueError("invalid address")
