#!/bin/bash

die() {
	echo "#####"
	echo $1
	echo "#####"
	exit 1
}

if [ $1 = "install" ]; then
	# fix lib location
	sed -e "s|/absolute/path/to/your/lib|${MY_INSTALLDIR}/lib|" -i ${MY_INSTALLDIR}/bin/LocalLib.cfg || die

	sed -e "s|/var/www/foswiki/|${MY_INSTALLDIR}/|g" -i ${MY_INSTALLDIR}/foswiki_httpd_conf.txt

	sed -e "s|http://your.domain.com|http://${VHOST_HOSTNAME}|g
			s|/home/httpd/foswiki|${MY_INSTALLDIR}|g
			s|# \$Foswiki::cfg{DefaultUrlHost}|\$Foswiki::cfg{DefaultUrlHost}|
			s|# \$Foswiki::cfg{DefaultUrlHost}|\$Foswiki::cfg{ScriptUrlPath}|
			s|# \$Foswiki::cfg{PubUrlPath}|\$Foswiki::cfg{PubUrlPath}|
			s|# \$Foswiki::cfg{PubDir}|\$Foswiki::cfg{PubDir}|
			s|# \$Foswiki::cfg{TemplateDir}|\$Foswiki::cfg{TemplateDir}|
			s|# \$Foswiki::cfg{DataDir}|\$Foswiki::cfg{DataDir}|
			s|# \$Foswiki::cfg{LocalesDir}|\$Foswiki::cfg{LocalesDir}|" -i ${MY_INSTALLDIR}/lib/Foswiki.spec

	# fix file permissions to avoid warnings
	chmod 0755 ${MY_INSTALLDIR}/bin/*
else
	echo $1
fi
